export interface ServerMessage {
  id: number;
  payload: string;
  completed?: boolean;
}

export interface ClientMessage {
  service: string;
  method: string;
  // generated by client
  id: number;
  payload: string;
  completed?: boolean;
}
