name: Playwright Tests (Extension only)
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/host
    container:
      image: mcr.microsoft.com/playwright:v1.31.1-focal
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/install_dependencies

      - name: Install dependencies
        run: pnpm install

      - name: Download clay-relay
        uses: robinraju/release-downloader@v1.7
        with:
          repository: "kenty02/clay-relay"
          tag: "v0.1.7"
          fileName: clay-relay_Linux_x86_64.tar.gz
          token: ${{ secrets.TOKEN_CLAY_RELAY }}
      - name: Extract clay-relay
        run: mkdir clay-relay && tar -xzf clay-relay_Linux_x86_64.tar.gz -C clay-relay
        working-directory: ./
      - name: Register clay-relay
        run: clay-relay/clay-relay --register
        working-directory: ./

      - name: Checkout test sites
        run: |
          mkdir -p test-sites
          git clone --depth 1 https://github.com/letsencrypt/website.git test-sites/letsencrypt
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.91.2'
          extended: true

      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}

      - name: Run Playwright tests with xvfb & test sites
        run: |
          cd test-sites/letsencrypt
          hugo server &
          pnpm dlx wait-port 1313
          cd ../..
          xvfb-run pnpm playwright test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: packages/host/playwright-report/
          retention-days: 30
